# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 11:52
from __future__ import unicode_literals

import apps.persons.models
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add-factlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='body_de',
            field=wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')), ('video', wagtail.wagtailembeds.blocks.EmbedBlock(icon='media')), ('Raw_HTML', wagtail.wagtailcore.blocks.StructBlock((('headline', wagtail.wagtailcore.blocks.CharBlock(length=256, required=False)), ('body', wagtail.wagtailcore.blocks.RawHTMLBlock())))), ('persons', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(classname='full title', required=False)), ('background', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('grey', 'grey'), ('white', 'white')])), ('personlist', wagtail.wagtailcore.blocks.ListBlock(apps.persons.models.PersonDisplayBlock)))))), blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='body_en',
            field=wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')), ('video', wagtail.wagtailembeds.blocks.EmbedBlock(icon='media')), ('Raw_HTML', wagtail.wagtailcore.blocks.StructBlock((('headline', wagtail.wagtailcore.blocks.CharBlock(length=256, required=False)), ('body', wagtail.wagtailcore.blocks.RawHTMLBlock())))), ('persons', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(classname='full title', required=False)), ('background', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('grey', 'grey'), ('white', 'white')])), ('personlist', wagtail.wagtailcore.blocks.ListBlock(apps.persons.models.PersonDisplayBlock)))))), null=True, verbose_name='Body'),
        ),
    ]
