# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_auto_20170612_1539"),
        ("projects", "0007_remove-person-bg"),
    ]

    operations = []
