# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectpage_custom_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='image',
        ),
    ]
