# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_projectpage_custom_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpage",
            name="partner",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="projectpage",
            name="timescale",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="projectpage",
            name="user_count",
            field=models.CharField(
                blank=True,
                max_length=256,
                verbose_name="Number of users per month",
            ),
        ),
    ]
