# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_auto_20170628_1747"),
        ("projects", "0011_add_aligned_image_block"),
    ]

    operations = []
