# Generated by Django 5.2.13 on 2026-05-28 09:14

import apps.persons.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_auto_20240702_1136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpage",
            name="body_de",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("image", 1),
                    ("aligned_image", 4),
                    ("Raw_HTML", 7),
                    ("persons", 10),
                    ("video_block", 16),
                    ("horizontal_gallery", 17),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "pilcrow"},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "icon": "image",
                            "template": "blocks/block_image.html",
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "center"),
                                ("left", "left"),
                                ("right", "right"),
                            ],
                            "help_text": "Decide on which side the image should be displayed",
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("display", 3)]],
                        {"icon": "image"},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 256, "required": False},
                    ),
                    6: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 5), ("body", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.ListBlock",
                        (apps.persons.models.PersonDisplayBlock,),
                        {},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 8), ("personlist", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 130, "required": False},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Please insert a short description of the video (character limit 500).",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Please upload or choose a media file with any of the following extensions: MP4, WebM, MP3, WAV"
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("audio", "Audio file"),
                                ("video", "Video file"),
                            ]
                        },
                    ),
                    15: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                            "help_text": "You can add the video's transcript here (unlimited characters).",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 11),
                                ("description", 12),
                                ("media", 13),
                                ("media_type", 14),
                                ("transcript", 15),
                            ]
                        ],
                        {},
                    ),
                    17: ("apps.core.blocks.HorizontalGalleryBlock", (), {}),
                },
                null=True,
                verbose_name="Body",
            ),
        ),
        migrations.AlterField(
            model_name="projectpage",
            name="body_en",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("image", 1),
                    ("aligned_image", 4),
                    ("Raw_HTML", 7),
                    ("persons", 10),
                    ("video_block", 16),
                    ("horizontal_gallery", 17),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "pilcrow"},
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "icon": "image",
                            "template": "blocks/block_image.html",
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "center"),
                                ("left", "left"),
                                ("right", "right"),
                            ],
                            "help_text": "Decide on which side the image should be displayed",
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("display", 3)]],
                        {"icon": "image"},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 256, "required": False},
                    ),
                    6: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 5), ("body", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.ListBlock",
                        (apps.persons.models.PersonDisplayBlock,),
                        {},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 8), ("personlist", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 130, "required": False},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Please insert a short description of the video (character limit 500).",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Please upload or choose a media file with any of the following extensions: MP4, WebM, MP3, WAV"
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("audio", "Audio file"),
                                ("video", "Video file"),
                            ]
                        },
                    ),
                    15: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                            "help_text": "You can add the video's transcript here (unlimited characters).",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 11),
                                ("description", 12),
                                ("media", 13),
                                ("media_type", 14),
                                ("transcript", 15),
                            ]
                        ],
                        {},
                    ),
                    17: ("apps.core.blocks.HorizontalGalleryBlock", (), {}),
                },
                null=True,
                verbose_name="Body",
            ),
        ),
    ]
