# Generated by Django 3.2.13 on 2022-08-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_customimage_file_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="alt_de",
            field=models.CharField(
                blank=True,
                help_text="Add an alternative text for image accessibility",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="alt_en",
            field=models.CharField(
                blank=True,
                help_text="Add an alternative text for image accessibility",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="customimage",
            name="copyright",
            field=models.CharField(
                blank=True,
                help_text="Add copyright information for image",
                max_length=255,
            ),
        ),
    ]
