# Generated by Django 5.2.2 on 2026-01-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0008_alter_customrendition_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="description",
            ),
        ),
    ]
