# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove-person-bg"),
        ("core", "0008_blogcategory_projectcategory"),
    ]

    operations = []
