# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_addresssettings_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresssettings',
            old_name='custom_image',
            new_name='image',
        ),
    ]
