# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_auto_20170907_1009"),
    ]

    operations = [
        migrations.AddField(
            model_name="addresssettings",
            name="map_link",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
