# Generated by Django 3.2.13 on 2022-09-01 10:41

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_add_submenu_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="subpages",
            field=wagtail.fields.StreamField(
                [
                    (
                        "submenuitem",
                        wagtail.blocks.StructBlock(
                            [
                                ("link", wagtail.blocks.PageChooserBlock()),
                                (
                                    "link_text_de",
                                    wagtail.blocks.CharBlock(max_length=255),
                                ),
                                (
                                    "link_text_en",
                                    wagtail.blocks.CharBlock(
                                        blank=True, max_length=255
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="These links will be displayed in a second level navigation.",
                null=True,
                use_json_field=True,
                verbose_name="Submenu",
            ),
        ),
    ]
