# Generated by Django 5.2.13 on 2026-06-03 10:34

import apps.core.blocks
import apps.persons.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_new_gallery_and_insights_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textpagewithblocks",
            name="body_de",
            field=wagtail.fields.StreamField(
                [
                    ("standard_paragraph", 1),
                    ("highlight_paragraph", 4),
                    ("quote_paragraph", 7),
                    ("single_image", 8),
                    ("image_slider", 10),
                    ("aligned_image", 13),
                    ("columns", 15),
                    ("linkbox", 21),
                    ("projects", 23),
                    ("ThreeImageLinks", 27),
                    ("Raw_HTML", 29),
                    ("Person", 32),
                    ("all_persons_list", 34),
                    ("teaser_list", 37),
                    ("video_block", 43),
                    ("main_insight", 50),
                    ("full_width_insight", 52),
                    ("project_cheat_sheet", 69),
                    ("horizontal_gallery", 70),
                    ("simple_item", 72),
                    ("cta_with_image", 79),
                    ("download_block", 86),
                    ("blog_block", 89),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"required": True},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 256, "required": False},
                    ),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 2), ("text", 0), ("link", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("green", "Gruen"),
                                ("orange", "Orange"),
                                ("red", "Rot"),
                            ],
                            "help_text": "Select a color from the list.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Please use an image with at least 800x400px or a similar aspect ratio.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 0),
                                ("color", 5),
                                ("image", 6),
                                ("author", 2),
                            ]
                        ],
                        {},
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "icon": "image",
                            "label": "Single image",
                            "template": "blocks/block_image.html",
                        },
                    ),
                    9: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    10: (
                        "wagtail.blocks.ListBlock",
                        (9,),
                        {
                            "help_text": "Responsive image slider(swipe on mobile). Please choose  4 images.",
                            "icon": "image",
                            "label": "Image Slider",
                            "template": "blocks/block_carousel.html",
                        },
                    ),
                    11: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "center"),
                                ("left", "left"),
                                ("right", "right"),
                            ],
                            "help_text": "Decide on which side the image should be displayed",
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 11), ("display", 12)]],
                        {},
                    ),
                    14: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("col1_headline", 2),
                                ("col1_text", 0),
                                ("col1_url", 14),
                                ("col2_headline", 2),
                                ("col2_text", 0),
                                ("col2_url", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"required": False},
                    ),
                    17: ("wagtail.blocks.PageChooserBlock", (), {}),
                    18: ("wagtail.blocks.CharBlock", (), {"max_length": 256}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("internal_link", 17), ("link_text", 18)]],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 2), ("text", 16), ("links", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.ListBlock",
                        (apps.core.blocks.ProjectBlock,),
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 2), ("projects", 22)]],
                        {},
                    ),
                    24: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": True},
                    ),
                    25: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"max_length": 256, "required": False},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 24),
                                ("internal_link", 3),
                                ("external_url", 25),
                                ("link_text", 18),
                            ]
                        ],
                        {"required": True},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image_left", 26),
                                ("image_middle", 26),
                                ("image_right", 26),
                            ]
                        ],
                        {},
                    ),
                    28: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 2), ("body", 28)]],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.ListBlock",
                        (apps.persons.models.PersonDisplayBlock,),
                        {},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 30), ("personlist", 31)]],
                        {},
                    ),
                    33: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 33)]],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 2), ("text", 0), ("url", 14)]],
                        {},
                    ),
                    36: ("wagtail.blocks.ListBlock", (35,), {}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 2), ("teasers", 36)]],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 130, "required": False},
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Please insert a short description of the video (character limit 500).",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Please upload or choose a media file with any of the following extensions: MP4, WebM, MP3, WAV"
                        },
                    ),
                    41: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("audio", "Audio file"),
                                ("video", "Video file"),
                            ]
                        },
                    ),
                    42: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                            "help_text": "You can add the video's transcript here (unlimited characters).",
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 38),
                                ("description", 39),
                                ("media", 40),
                                ("media_type", 41),
                                ("transcript", 42),
                            ]
                        ],
                        {},
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Short label shown above the value (e.g. topic name).",
                            "label": "Category",
                            "max_length": 128,
                            "required": True,
                        },
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Primary figure or short headline (e.g. a number).",
                            "label": "Value",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Supporting text describing the insight.",
                            "label": "Information",
                            "max_length": 256,
                            "required": True,
                        },
                    ),
                    47: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional URL. Makes the category and value clickable.",
                            "label": "Link",
                            "max_length": 512,
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category", 44),
                                ("value", 45),
                                ("information", 46),
                                ("link", 47),
                            ]
                        ],
                        {},
                    ),
                    49: (
                        "wagtail.blocks.ListBlock",
                        (48,),
                        {"label": "Insight cards", "min_num": 1},
                    ),
                    50: ("wagtail.blocks.StructBlock", [[("items", 49)]], {}),
                    51: (
                        "wagtail.blocks.ListBlock",
                        (48,),
                        {"label": "Insight columns", "min_num": 1},
                    ),
                    52: ("wagtail.blocks.StructBlock", [[("items", 51)]], {}),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "URL",
                            "label": "URL heading",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    54: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "URL", "required": False},
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Display text for the link. Defaults to the URL.",
                            "label": "Link text",
                            "max_length": 256,
                            "required": False,
                        },
                    ),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Project partners",
                            "label": "Project partners heading",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Project partners",
                            "max_length": 512,
                            "required": False,
                        },
                    ),
                    58: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Zeitraum",
                            "label": "Timescale heading",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Timescale",
                            "max_length": 512,
                            "required": False,
                        },
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Contact",
                            "label": "Contact heading",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Name", "max_length": 128, "required": True},
                    ),
                    62: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link URL", "required": False},
                    ),
                    63: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Internal page", "required": False},
                    ),
                    64: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Optional, e.g. "he/him" (parentheses are added automatically).',
                            "label": "Pronouns",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 61),
                                ("link", 62),
                                ("page", 63),
                                ("pronouns", 64),
                            ]
                        ],
                        {},
                    ),
                    66: (
                        "wagtail.blocks.ListBlock",
                        (65,),
                        {"label": "Contacts", "required": False},
                    ),
                    67: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Large introductory quote shown beside the fact list.",
                            "label": "Intro quote",
                            "required": False,
                        },
                    ),
                    68: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Supporting paragraph below the intro quote.",
                            "label": "Intro text",
                            "required": False,
                        },
                    ),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("url_label", 53),
                                ("url", 54),
                                ("url_text", 55),
                                ("partners_label", 56),
                                ("partners", 57),
                                ("timescale_label", 58),
                                ("timescale", 59),
                                ("contact_label", 60),
                                ("contacts", 66),
                                ("intro_quote", 67),
                                ("intro_text", 68),
                            ]
                        ],
                        {},
                    ),
                    70: ("apps.core.blocks.HorizontalGalleryBlock", (), {}),
                    71: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Title",
                            "max_length": 128,
                            "required": True,
                        },
                    ),
                    72: ("wagtail.blocks.StructBlock", [[("title", 71)]], {}),
                    73: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Category",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    74: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Image on the left inside the frame (approx. 294×294px or square).",
                            "required": True,
                        },
                    ),
                    75: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Add either an internal or external link (external wins).",
                            "required": False,
                        },
                    ),
                    76: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "External link", "required": False},
                    ),
                    77: (
                        "wagtail.blocks.StructBlock",
                        [[("internal_link", 75), ("external_link", 76)]],
                        {"required": False},
                    ),
                    78: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Button text",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category", 73),
                                ("title", 71),
                                ("image", 74),
                                ("link", 77),
                                ("link_text", 78),
                            ]
                        ],
                        {},
                    ),
                    80: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Title",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    81: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Optional image on the left (approx. 294×294px or square).",
                            "label": "Image",
                            "required": False,
                        },
                    ),
                    82: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "File", "required": True},
                    ),
                    83: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Defaults to the document title.",
                            "label": "Button label",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    84: (
                        "wagtail.blocks.StructBlock",
                        [[("file", 82), ("button_label", 83)]],
                        {},
                    ),
                    85: (
                        "wagtail.blocks.ListBlock",
                        (84,),
                        {
                            "label": "Download files",
                            "max_num": 2,
                            "min_num": 1,
                        },
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category", 73),
                                ("title", 80),
                                ("image", 81),
                                ("downloads", 85),
                            ]
                        ],
                        {},
                    ),
                    87: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Blog post",
                            "page_type": ["blog.BlogPage"],
                            "required": True,
                        },
                    ),
                    88: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Button",
                            "label": "Button text",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [[("post", 87), ("link_text", 88)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="Body",
            ),
        ),
        migrations.AlterField(
            model_name="textpagewithblocks",
            name="body_en",
            field=wagtail.fields.StreamField(
                [
                    ("standard_paragraph", 1),
                    ("highlight_paragraph", 4),
                    ("quote_paragraph", 7),
                    ("single_image", 8),
                    ("image_slider", 10),
                    ("aligned_image", 13),
                    ("columns", 15),
                    ("linkbox", 21),
                    ("projects", 23),
                    ("ThreeImageLinks", 27),
                    ("Raw_HTML", 29),
                    ("Person", 32),
                    ("all_persons_list", 34),
                    ("teaser_list", 37),
                    ("video_block", 43),
                    ("main_insight", 50),
                    ("full_width_insight", 52),
                    ("project_cheat_sheet", 69),
                    ("horizontal_gallery", 70),
                    ("simple_item", 72),
                    ("cta_with_image", 79),
                    ("download_block", 86),
                    ("blog_block", 89),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"required": True},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("text", 0)]], {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 256, "required": False},
                    ),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 2), ("text", 0), ("link", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("green", "Gruen"),
                                ("orange", "Orange"),
                                ("red", "Rot"),
                            ],
                            "help_text": "Select a color from the list.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Please use an image with at least 800x400px or a similar aspect ratio.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 0),
                                ("color", 5),
                                ("image", 6),
                                ("author", 2),
                            ]
                        ],
                        {},
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "icon": "image",
                            "label": "Single image",
                            "template": "blocks/block_image.html",
                        },
                    ),
                    9: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    10: (
                        "wagtail.blocks.ListBlock",
                        (9,),
                        {
                            "help_text": "Responsive image slider(swipe on mobile). Please choose  4 images.",
                            "icon": "image",
                            "label": "Image Slider",
                            "template": "blocks/block_carousel.html",
                        },
                    ),
                    11: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "center"),
                                ("left", "left"),
                                ("right", "right"),
                            ],
                            "help_text": "Decide on which side the image should be displayed",
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 11), ("display", 12)]],
                        {},
                    ),
                    14: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("col1_headline", 2),
                                ("col1_text", 0),
                                ("col1_url", 14),
                                ("col2_headline", 2),
                                ("col2_text", 0),
                                ("col2_url", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"required": False},
                    ),
                    17: ("wagtail.blocks.PageChooserBlock", (), {}),
                    18: ("wagtail.blocks.CharBlock", (), {"max_length": 256}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("internal_link", 17), ("link_text", 18)]],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 2), ("text", 16), ("links", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.ListBlock",
                        (apps.core.blocks.ProjectBlock,),
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 2), ("projects", 22)]],
                        {},
                    ),
                    24: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": True},
                    ),
                    25: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"max_length": 256, "required": False},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 24),
                                ("internal_link", 3),
                                ("external_url", 25),
                                ("link_text", 18),
                            ]
                        ],
                        {"required": True},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image_left", 26),
                                ("image_middle", 26),
                                ("image_right", 26),
                            ]
                        ],
                        {},
                    ),
                    28: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 2), ("body", 28)]],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.ListBlock",
                        (apps.persons.models.PersonDisplayBlock,),
                        {},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 30), ("personlist", 31)]],
                        {},
                    ),
                    33: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 33)]],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 2), ("text", 0), ("url", 14)]],
                        {},
                    ),
                    36: ("wagtail.blocks.ListBlock", (35,), {}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 2), ("teasers", 36)]],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 130, "required": False},
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Please insert a short description of the video (character limit 500).",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Please upload or choose a media file with any of the following extensions: MP4, WebM, MP3, WAV"
                        },
                    ),
                    41: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("audio", "Audio file"),
                                ("video", "Video file"),
                            ]
                        },
                    ),
                    42: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                            "help_text": "You can add the video's transcript here (unlimited characters).",
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 38),
                                ("description", 39),
                                ("media", 40),
                                ("media_type", 41),
                                ("transcript", 42),
                            ]
                        ],
                        {},
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Short label shown above the value (e.g. topic name).",
                            "label": "Category",
                            "max_length": 128,
                            "required": True,
                        },
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Primary figure or short headline (e.g. a number).",
                            "label": "Value",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Supporting text describing the insight.",
                            "label": "Information",
                            "max_length": 256,
                            "required": True,
                        },
                    ),
                    47: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional URL. Makes the category and value clickable.",
                            "label": "Link",
                            "max_length": 512,
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category", 44),
                                ("value", 45),
                                ("information", 46),
                                ("link", 47),
                            ]
                        ],
                        {},
                    ),
                    49: (
                        "wagtail.blocks.ListBlock",
                        (48,),
                        {"label": "Insight cards", "min_num": 1},
                    ),
                    50: ("wagtail.blocks.StructBlock", [[("items", 49)]], {}),
                    51: (
                        "wagtail.blocks.ListBlock",
                        (48,),
                        {"label": "Insight columns", "min_num": 1},
                    ),
                    52: ("wagtail.blocks.StructBlock", [[("items", 51)]], {}),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "URL",
                            "label": "URL heading",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    54: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "URL", "required": False},
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Display text for the link. Defaults to the URL.",
                            "label": "Link text",
                            "max_length": 256,
                            "required": False,
                        },
                    ),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Project partners",
                            "label": "Project partners heading",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Project partners",
                            "max_length": 512,
                            "required": False,
                        },
                    ),
                    58: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Zeitraum",
                            "label": "Timescale heading",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Timescale",
                            "max_length": 512,
                            "required": False,
                        },
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Contact",
                            "label": "Contact heading",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Name", "max_length": 128, "required": True},
                    ),
                    62: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link URL", "required": False},
                    ),
                    63: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Internal page", "required": False},
                    ),
                    64: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Optional, e.g. "he/him" (parentheses are added automatically).',
                            "label": "Pronouns",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 61),
                                ("link", 62),
                                ("page", 63),
                                ("pronouns", 64),
                            ]
                        ],
                        {},
                    ),
                    66: (
                        "wagtail.blocks.ListBlock",
                        (65,),
                        {"label": "Contacts", "required": False},
                    ),
                    67: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Large introductory quote shown beside the fact list.",
                            "label": "Intro quote",
                            "required": False,
                        },
                    ),
                    68: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Supporting paragraph below the intro quote.",
                            "label": "Intro text",
                            "required": False,
                        },
                    ),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("url_label", 53),
                                ("url", 54),
                                ("url_text", 55),
                                ("partners_label", 56),
                                ("partners", 57),
                                ("timescale_label", 58),
                                ("timescale", 59),
                                ("contact_label", 60),
                                ("contacts", 66),
                                ("intro_quote", 67),
                                ("intro_text", 68),
                            ]
                        ],
                        {},
                    ),
                    70: ("apps.core.blocks.HorizontalGalleryBlock", (), {}),
                    71: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Title",
                            "max_length": 128,
                            "required": True,
                        },
                    ),
                    72: ("wagtail.blocks.StructBlock", [[("title", 71)]], {}),
                    73: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Category",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    74: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Image on the left inside the frame (approx. 294×294px or square).",
                            "required": True,
                        },
                    ),
                    75: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Add either an internal or external link (external wins).",
                            "required": False,
                        },
                    ),
                    76: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "External link", "required": False},
                    ),
                    77: (
                        "wagtail.blocks.StructBlock",
                        [[("internal_link", 75), ("external_link", 76)]],
                        {"required": False},
                    ),
                    78: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Button text",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category", 73),
                                ("title", 71),
                                ("image", 74),
                                ("link", 77),
                                ("link_text", 78),
                            ]
                        ],
                        {},
                    ),
                    80: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Title",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    81: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Optional image on the left (approx. 294×294px or square).",
                            "label": "Image",
                            "required": False,
                        },
                    ),
                    82: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "File", "required": True},
                    ),
                    83: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Defaults to the document title.",
                            "label": "Button label",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    84: (
                        "wagtail.blocks.StructBlock",
                        [[("file", 82), ("button_label", 83)]],
                        {},
                    ),
                    85: (
                        "wagtail.blocks.ListBlock",
                        (84,),
                        {
                            "label": "Download files",
                            "max_num": 2,
                            "min_num": 1,
                        },
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("category", 73),
                                ("title", 80),
                                ("image", 81),
                                ("downloads", 85),
                            ]
                        ],
                        {},
                    ),
                    87: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "label": "Blog post",
                            "page_type": ["blog.BlogPage"],
                            "required": True,
                        },
                    ),
                    88: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Button",
                            "label": "Button text",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [[("post", 87), ("link_text", 88)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="Body",
            ),
        ),
    ]
