# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 12:31
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_update_tags"),
        ("blog", "0006_add_aligned_image_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="categories",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="core.BlogCategory"
            ),
        ),
    ]
