# Generated by Django 3.2.13 on 2022-08-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('academy', '0006_change_blogpost_to_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_text_en', models.CharField(max_length=255, verbose_name='intro text en')),
                ('intro_text_de', models.CharField(blank=True, max_length=255, verbose_name='intro text de')),
                ('intro_link_text_en', models.CharField(blank=True, max_length=100, verbose_name='intro link text en')),
                ('intro_link_text_de', models.CharField(blank=True, max_length=100, verbose_name='intro link text de')),
                ('intro_link', models.ForeignKey(blank=True, help_text='Choose the page the intro text links to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Academy Landing Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
