# Generated by Django 3.2.13 on 2022-08-29 11:53

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0013_add_topic_block_to_landing_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academychallengepage",
            name="teaser_de",
            field=wagtail.fields.StreamField(
                [
                    (
                        "call_to_action_teaser",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "columns",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "headline",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=28,
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        help_text="Please add image with transparent background",
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "body_text",
                                                    wagtail.blocks.TextBlock(
                                                        max_length=120,
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "cta_link",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            (
                                                                "internal_link",
                                                                wagtail.blocks.PageChooserBlock(
                                                                    help_text="The external link overwrites the link to a local page. Please only add 1 link.",
                                                                    required=False,
                                                                ),
                                                            ),
                                                            (
                                                                "external_link",
                                                                wagtail.blocks.URLBlock(
                                                                    required=False
                                                                ),
                                                            ),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "link_text",
                                                    wagtail.blocks.CharBlock(
                                                        label="Link Text",
                                                        max_length=28,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "anchor_link",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Anchor link should be all one word.",
                                                        label="Anchor Link",
                                                        max_length=28,
                                                        required=False,
                                                    ),
                                                ),
                                            ],
                                            label="List and Image",
                                        ),
                                        max_num=2,
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Teaser",
            ),
        ),
        migrations.AlterField(
            model_name="academychallengepage",
            name="teaser_en",
            field=wagtail.fields.StreamField(
                [
                    (
                        "call_to_action_teaser",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "columns",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "headline",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=28,
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        help_text="Please add image with transparent background",
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "body_text",
                                                    wagtail.blocks.TextBlock(
                                                        max_length=120,
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "cta_link",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            (
                                                                "internal_link",
                                                                wagtail.blocks.PageChooserBlock(
                                                                    help_text="The external link overwrites the link to a local page. Please only add 1 link.",
                                                                    required=False,
                                                                ),
                                                            ),
                                                            (
                                                                "external_link",
                                                                wagtail.blocks.URLBlock(
                                                                    required=False
                                                                ),
                                                            ),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "link_text",
                                                    wagtail.blocks.CharBlock(
                                                        label="Link Text",
                                                        max_length=28,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "anchor_link",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Anchor link should be all one word.",
                                                        label="Anchor Link",
                                                        max_length=28,
                                                        required=False,
                                                    ),
                                                ),
                                            ],
                                            label="List and Image",
                                        ),
                                        max_num=2,
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Teaser",
            ),
        ),
        migrations.AlterField(
            model_name="academyindexpage",
            name="body_en",
            field=wagtail.fields.StreamField(
                [
                    (
                        "call_to_action_teaser",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "columns",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "headline",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=28,
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        help_text="Please add image with transparent background",
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "body_text",
                                                    wagtail.blocks.TextBlock(
                                                        max_length=120,
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "cta_link",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            (
                                                                "internal_link",
                                                                wagtail.blocks.PageChooserBlock(
                                                                    help_text="The external link overwrites the link to a local page. Please only add 1 link.",
                                                                    required=False,
                                                                ),
                                                            ),
                                                            (
                                                                "external_link",
                                                                wagtail.blocks.URLBlock(
                                                                    required=False
                                                                ),
                                                            ),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "link_text",
                                                    wagtail.blocks.CharBlock(
                                                        label="Link Text",
                                                        max_length=28,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "anchor_link",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Anchor link should be all one word.",
                                                        label="Anchor Link",
                                                        max_length=28,
                                                        required=False,
                                                    ),
                                                ),
                                            ],
                                            label="List and Image",
                                        ),
                                        max_num=2,
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Body",
            ),
        ),
        migrations.AlterField(
            model_name="academypage",
            name="teaser_en",
            field=wagtail.fields.StreamField(
                [
                    (
                        "call_to_action_teaser",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "columns",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "headline",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=28,
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        help_text="Please add image with transparent background",
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "body_text",
                                                    wagtail.blocks.TextBlock(
                                                        max_length=120,
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "cta_link",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            (
                                                                "internal_link",
                                                                wagtail.blocks.PageChooserBlock(
                                                                    help_text="The external link overwrites the link to a local page. Please only add 1 link.",
                                                                    required=False,
                                                                ),
                                                            ),
                                                            (
                                                                "external_link",
                                                                wagtail.blocks.URLBlock(
                                                                    required=False
                                                                ),
                                                            ),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "link_text",
                                                    wagtail.blocks.CharBlock(
                                                        label="Link Text",
                                                        max_length=28,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "anchor_link",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Anchor link should be all one word.",
                                                        label="Anchor Link",
                                                        max_length=28,
                                                        required=False,
                                                    ),
                                                ),
                                            ],
                                            label="List and Image",
                                        ),
                                        max_num=2,
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Body",
            ),
        ),
    ]
