# Generated by Django 3.2.13 on 2022-08-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_add_column_teaser_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academylandingpage',
            name='color1',
            field=models.CharField(default='#eee8aa', max_length=7),
        ),
        migrations.AlterField(
            model_name='academylandingpage',
            name='color2',
            field=models.CharField(default='#e1bcbd', max_length=7),
        ),
    ]
