# Generated by Django 3.2.13 on 2022-09-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_auto_20220830_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academyexternallink',
            name='academy_content_type',
            field=models.CharField(blank=True, choices=[('WS', 'workshop'), ('AR', 'article'), ('VD', 'video'), ('EV', 'event'), ('LL', 'link collection')], max_length=2),
        ),
        migrations.AlterField(
            model_name='academypage',
            name='academy_content_type',
            field=models.CharField(blank=True, choices=[('WS', 'workshop'), ('AR', 'article'), ('VD', 'video'), ('EV', 'event'), ('LL', 'link collection')], max_length=2),
        ),
    ]
