# Generated by Django 3.2.13 on 2023-02-20 11:10

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0022_fix_image_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academyindexpage",
            name="intro_en",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="intro text"
            ),
        ),
        migrations.AlterField(
            model_name="academypage",
            name="intro_en",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="Teasertext"
            ),
        ),
    ]
