# Generated by Django 3.2.18 on 2024-07-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0023_alter_academyindexpage_and_academypage_intro_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academyexternallink",
            name="academy_content_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WS", "workshop"),
                    ("AR", "article"),
                    ("VD", "video"),
                    ("LL", "link collection"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="academypage",
            name="academy_content_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WS", "workshop"),
                    ("AR", "article"),
                    ("VD", "video"),
                    ("LL", "link collection"),
                ],
                max_length=2,
            ),
        ),
    ]
