# Generated by Django 5.2.2 on 2026-01-14 10:56

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0024_auto_20240701_1634"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academypage",
            name="topics",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("LT", "Liquid Democracy: Theory & Vision"),
                    ("DS", "Digital Civic Society"),
                    ("PA", "Digital Participation In Action"),
                ],
                max_length=8,
            ),
        ),
    ]
