# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20150716_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
